### PR TITLE
Alternative image documentation

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Adds advanced topic alternative image

Documentation for feature pull request kubenow/kubenow#383

### CODE REVIEW

**Comment by carmat88** [comment]
Looking at it now. Cheers!

**Comment by carmat88** [comment]
Hej @andersla . Let me know what you think about the latest revisions. If they are correct and you second them, please feel free to go ahead and merge this PR. Cheers.

**Comment by andersla** [comment]
Looks great! Thanks for your excellent improvements!!

**Comment by andersla** [comment]
Ooops, the function is not merged yet, but I think @mcapuccini said the function in KubeNow was ready to go:-)

**Comment by mcapuccini** [comment]
Thanks for sorting it out. @andersla sure you can go ahead and merge your PR 🙂

**Pull request merged**
