### PR TITLE
Add configurable ingress ports to docs

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Adds configurable ingress ports to docs

### CODE REVIEW

**Comment by carmat88** [comment]
Hey @andersla . LGTM, thanks. Since I am not assigned yet as a reviewer, please feel free to merge it. Nevertheless, I was wondering the following. Do you think this would require also a separated doc page in the _Advanced Topics_ section, or would this be enough to know for a user? Cheers!

**Comment by andersla** [comment]
Maybe advanced topic is better? Or what do you think? It is relatively rare having to open other port?

**Comment by carmat88** [comment]
> Maybe advanced topic is better? Or what do you think? It is relatively rare having to open other port?

Yeah, I have the feeling it may be better, in particular given its optional/rare nature. Nevertheless, your changes are relevant and useful of course. I will add a commit with the changes within the _Advanced Topics_ section and doubke-check what you'll think of them.

**Comment by carmat88** [comment]
Hey @andersla I've created the doc under the _Advanced Topics_ section. What do you think? Could you please go thorough it and give me your opinion? Many thanks. Cheers!

**Comment by andersla** [comment]
I made some small edits to your Advanced topic, and removed my parameters from the simpler bootstrap exampl.

**Comment by mcapuccini** [comment]
It seems like you didn't run CI for this PR. Docs building is failing, could you give it a look?

**Comment by mcapuccini** [comment]
I am trying to rebuild it now. Perhaps it was just a temporary issue.

**Pull request merged**
