### PR TITLE
Adds documentation for kn-scale command

### PR DESCRIPTION
**Pull request by andersla**
## Change content and motivation
Adds documentation for kn-scale command

Connects to PR kubenow/kubenow#384

### CODE REVIEW

**Comment by carmat88** [comment]
Same here, looking at it now. Cheers!

**Comment by carmat88** [comment]
Hello again @andersla . Please let me know what you think about latest revisions. If you concur, then feel free to merge it, otherwise to change it as you see fit (considering availability of such function :-) ). Cheers!

**Comment by andersla** [comment]
I like changes a lot! Waiting to merge until  kubenow/kubenow#384

**Review by carmat88 — APPROVED** [review]
LGTM. Cheers.

**Pull request merged**
